# Full Country List


[
    "Botswana",
    "Senegal",
    "South Africa",
    "Bangladesh",
    "Cambodia",
    "India",
    "Indonesia",
    "Israel",
    "Japan",
    "Malaysia",
    "Mongolia",
    "Philippines",
    "Russia",
    "Singapore",
    "Taiwan",
    "Thailand",
    "Belgium",
    "Bulgaria",
    "Croatia",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Netherlands",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "Ukraine",
    "United Kingdom",
    "Canada",
    "Greenland",
    "Mexico",
    "United States",
    "Australia",
    "New Zealand",
    "Argentina",
    "Bolivia",
    "Brazil",
    "Chile",
    "Colombia",
    "Ecuador",
    "Peru",
    "Uruguay",
]
